name: Download File and Release

on:
  workflow_dispatch:  # 手动触发
  push:
    tags:
      - "v*"  # 通过 tag 触发（可选）

jobs:
  download-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download File
      run: |
        # 使用代理或镜像（可选）
        # 例如替换域名：将 fastly.net 替换为国内可访问的镜像
        # curl -L -o nexus.zip "https://sonatype-download.example-mirror.com/.../nexus-3.78.0-14-win64.zip"
        
        # 直接下载（如果 GitHub Actions 服务器可访问）
        curl -L -o nexus.zip "https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.78.0-14-win64.zip"

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: nexus.zip  # 上传的文件名
        tag_name: v1.0.0  # Release 的标签（可动态生成）
        name: "Nexus Release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的权限 Token
