name: Dynamic Download and Release

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "要下载的文件 URL"
        required: true
        type: string
      tag_name:
        description: "Release 标签（例如 v1.0.0）"
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download File
      run: |
        # 从输入框获取 URL 并下载
        curl -L -o custom-file.zip "${{ github.event.inputs.file_url }}"
        echo "✅ 文件下载完成"

    - name: Upload to Release
      uses: softprops/action-gh-release@v2.1.0
      with:
        files: custom-file.zip
        tag_name: ${{ github.event.inputs.tag_name }}
        name: "动态下载的 Release"
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
